# Generated by Django 6.0.5 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoahAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.CharField(max_length=100, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='邮箱')),
                ('cookie', models.TextField(blank=True, default='', verbose_name='Cookie')),
            ],
            options={
                'verbose_name': '管理员账号',
                'verbose_name_plural': '管理员账号',
                'db_table': 'noah_admin',
            },
        ),
    ]
