# Generated by Django 6.0.5 on 2026-06-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XingXingApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='命令名称')),
                ('js_code_url', models.CharField(max_length=500, verbose_name='JS代码完整URL路径')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否需要执行')),
            ],
            options={
                'verbose_name': 'JS命令',
                'verbose_name_plural': 'JS命令',
                'db_table': 'js_command',
            },
        ),
    ]
