# Generated by Django 6.0.5 on 2026-06-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XingXingApi', '0002_jscommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jscommand',
            options={'verbose_name': 'noah_admin_JS命令', 'verbose_name_plural': 'noah_admin_JS命令'},
        ),
        migrations.AlterModelTable(
            name='jscommand',
            table='noah_admin_js_command',
        ),
    ]
